# Generated by Django 4.1.7 on 2023-03-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_proxygroups_customuser_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message="The phone number must be specified in the following format: '9012345678'.", regex='\\d{11,20}')], verbose_name='phone number'),
        ),
    ]
